# Generated by Selenium IDE
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import time
import unittest
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager

#User to access the polls page  
class TestAccesspollspage(unittest.TestCase):
        def setUp(self):
            chrome_options = Options()
            chrome_options.add_argument("--headless")
            self.driver = webdriver.Chrome(ChromeDriverManager().install())
            self.vars = {}
  
        def tearDown(self):
            self.driver.quit()
  
        def test_accesspollspage(self):
    # Test name: access polls page
    # Step # | name | target | value
    # 1 | open | /polls/ |
            self.driver.get("http://127.0.0.1:8000/polls/")
    # 2 | setWindowSize | 750x824 | 
            self.driver.set_window_size(750, 824)
    # 3 | click | css=html | 
            self.driver.find_element(By.CSS_SELECTOR, "html").click()
    # 4 | click | css=body | 
            self.driver.find_element(By.CSS_SELECTOR, "body").click()
            self.assertIn("Detail", self.driver.title)
# User to select what's my age page
# user will then select a number (32) and vote.
'''class TestSelectwhatsage(unittest.TestCase):
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}
  
    def teardown_method(self, method):
        self.driver.quit()
  
    def test_selectwhatsage(self):
    # Test name: select whats age
    # Step # | name | target | value
    # 1 | open | /polls/ | 
        self.driver.get("http://127.0.0.1:8000/polls/")
    # 2 | setWindowSize | 752x824 | 
        self.driver.set_window_size(752, 824)
    # 3 | click | linkText=What's your age? | 
        self.driver.find_element(By.LINK_TEXT, "What\'s your age?").click()
    # 4 | click | id=choice | 
        self.driver.find_element(By.ID, "choice").click()
    # 5 | click | css=input:nth-child(11) | 
        self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(11)").click()

    #user will select what my name, and select Alan and press vote.
    
class TestSelectwhatsyourname():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_selectwhatsyourname(self):
    # Test name: select whats your name
    # Step # | name | target | value
    # 1 | open | /polls/ | 
    self.driver.get("http://127.0.0.1:8000/polls/")
    # 2 | setWindowSize | 752x824 | 
    self.driver.set_window_size(752, 824)
    # 3 | click | linkText=what's your name? | 
    self.driver.find_element(By.LINK_TEXT, "what\'s your name?").click()
    # 4 | click | xpath=(//input[@id='choice'])[3] | 
    self.driver.find_element(By.XPATH, "(//input[@id=\'choice\'])[3]").click()
    # 5 | click | css=input:nth-child(11) | 
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(11)").click()
  
'''